PFAVersionFinale/Models/Publication.cs
namespace PFAVersionFinale.Models
{
    public class Publication
    {
        public int PublicationId { get; set; }
        public string Libelle { get; set; }
        public DateTime DatePub { get; set; }
        public string Description { get; set; }
        public string TypePublication { get; set; }
        public List<User>? Users { get; set; }
        public List<WebMaster>? WebMasters { get; set; }
        public List<Ouvrier>? Ouvrier { get; set; }
        public List<Client>? Clients { get; set; }
    }
}

PFAVersionFinale/Controllers/PublicationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PFAVersionFinale.Models;
namespace PFAVersionFinale.Controllers
{
    public class PublicationsController : Controller
    {
        MyContexte db;
        public PublicationsController(MyContexte db)
        {
            this.db = db;
        }
        public IActionResult IndexPublication()
        {
            List<Publication> publications = db.Publications.ToList();
            return View(publications);
        }
        public IActionResult AddPublication()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddPublication(Publication publication)
        {
            if(ModelState.IsValid)
            {
                db.Publications.Add(publication);
                db.SaveChanges();
                return RedirectToAction("IndexPublication");
            }
            return View();
        }
        public IActionResult EditPublication(int id)
        {
            Publication publication = db.Publications.Where(pub => pub.PublicationId == id).FirstOrDefault();
            if (publication != null)
            {
                return View(publication);
            }
            return RedirectToAction("IndexPublication");
        }
        [HttpPost]
        public IActionResult EditPublication(Publication model)
        {
            if (ModelState.IsValid)
            {
                Publication publication = db.Publications.Where(pub => pub.PublicationId == model.PublicationId).FirstOrDefault();
                if (publication != null)
                {
                    publication.Libelle = model.Libelle;
                    publication.DatePub = model.DatePub;
                    publication.Description = model.Description;
                    db.SaveChanges();
                    return RedirectToAction("IndexPublication");
                }
            }
            return View(model);
        }
        public IActionResult DeletePublication(int id)
        {
            Publication publication = db.Publications.Where(pub => pub.PublicationId == id).FirstOrDefault();
            if (publication != null)
            {
                db.Publications.Remove(publication);
                db.SaveChanges();
            }
            return RedirectToAction("IndexPublication");
        }
    }
}

PFAVersionFinale/Views/Publications/AddPublication.cshtml
@model PFAVersionFinale.Models.Publication

@{
    ViewData["Title"] = "AddPublication";
    Layout = "";
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Ajouter Service</title>
	<style type="text/css">
		* {
			margin: 0;
			padding: 0;
			box-sizing: border-box;
			font-family: 'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;
		}

		body {
			color: #fff;
			display: flex;
			height: 100vh;
			justify-content: center;
			align-items: center;
			background: linear-gradient(135deg,#0000FF,#79F8F8);
			padding: 10px;
		}

		.container {
			max-width: 700px;
			width: 100%;
			padding: 25px 30px;
			border-radius: 25px;
			background: linear-gradient(135deg,#1E7FCB,#007FFF);
		}

			.container .heading {
				font-size: 25px;
				font-weight: 500;
				position: relative;
				text-align: center;
				padding: 0 0 20px 0;
			}

				.container .heading::before {
					content: '';
					position: absolute;
					height: 3px;
					left: 0;
					bottom: 0;
					width: 100%;
					background: linear-gradient(135deg,#0000FF,#79F8F8);
				}

			.container form .card-details {
				margin-top: 25px;
				display: flex;
				flex-wrap: wrap;
				justify-content: space-between;
			}

		form .card-details .card-box {
			width: calc(100% / 2 - 20px);
			margin-bottom: 15px;
		}

		.card-details .card-box .details {
			display: block;
			font-weight: 500;
			margin-bottom: 5px;
		}

		.card-details .card-box input {
			height: 45px;
			width: 100%;
			outline: none;
			border-radius: 5px;
			border: 1px solid #ccc;
			padding-left: 15px;
			font-size: 16px;
			border-bottom: 2px;
			transition: all 0.3s ease;
		}

			.card-details .card-box input:focus,
			.card-details .card-box input:valid {
				border-color: #9b59b6;
			}

		form .circal-form .circal-title {
			font-size: 20px;
			font-weight: 500;
			border-bottom: 2px solid;
		}

		form .circal-form .category {
			margin-top: 10px;
			margin-bottom: 10px;
		}

		form .button {
			text-align: center;
		}

			form .button input {
				padding: 10px 0;
				margin-top: 10px;
				height: 100%;
				width: 50%;
				outline: none;
				border: none;
				font-size: 18px;
				color: #fff;
				font-weight: 500;
				border-radius: 5px;
				letter-spacing: 1px;
				background: linear-gradient(135deg,#0000FF,#79F8F8);
			}
	</style>
</head>
<body>
	<div class="container">
		<div class="heading">Information sur la Publication</div>
		<form asp-action="AddPublication" method="post" asp-controller="Publications">
			<div class="card-details">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group">
					<label asp-for="Libelle" class="control-label"></label>
					<input asp-for="Libelle" class="form-control" />
					<span asp-validation-for="Libelle" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="DatePub" class="control-label"></label>
					<input asp-for="DatePub" class="form-control" />
					<span asp-validation-for="DatePub" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Description" class="control-label"></label>
					<input asp-for="Description" class="form-control" />
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="TypePublication" class="control-label"></label>
					<input asp-for="TypePublication" class="form-control" />
					<span asp-validation-for="TypePublication" class="text-danger"></span>
				</div>
			</div>
			<div class="btn btn-primary">
				<div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
			</div>
		</form>
	</div>
</body>
</html>

PFAVersionFinale/Views/Publications/DeletePublication.cshtml
@model PFAVersionFinale.Models.Publication

@{
    ViewData["Title"] = "DeletePublication";
    Layout = "";
}

<h1>DeletePublication</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Publication</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Libelle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatePub)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatePub)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypePublication)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypePublication)
        </dd>
    </dl>
    
    <form asp-action="DeletePublication">
        <input type="hidden" asp-for="PublicationId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PFAVersionFinale/Views/Publications/EditPublication.cshtml
@model PFAVersionFinale.Models.Publication

@{
    ViewData["Title"] = "EditPublication";
}

<h1>EditPublication</h1>

<h4>Publication</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPublication">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PublicationId" />
            <div class="form-group">
                <label asp-for="Libelle" class="control-label"></label>
                <input asp-for="Libelle" class="form-control" />
                <span asp-validation-for="Libelle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatePub" class="control-label"></label>
                <input asp-for="DatePub" class="form-control" />
                <span asp-validation-for="DatePub" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypePublication" class="control-label"></label>
                <input asp-for="TypePublication" class="form-control" />
                <span asp-validation-for="TypePublication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}