PFAVersionFinale/Models/Vote.cs
namespace PFAVersionFinale.Models
{
    public class Vote
    {
        public int VoteId { get; set; }
        public DateTime DateVote { get; set; }
        public string NoteVote { get; set; }
    }
}

PFAVersionFinale/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using PFAVersionFinale.Models;
namespace PFAVersionFinale.Controllers
{
    public class ServicesController : Controller
    {
        MyContexte db;
        public ServicesController(MyContexte db)
        {
            this.db = db;
        }
        public IActionResult IndexServices()
        {
            List<Service> services = db.Services.ToList();
            return View(services);
        }
        public IActionResult AddServices()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddServices(Service service)
        {
            if (ModelState.IsValid)
            {
                db.Services.Add(service);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [Route("Services/EditServices/{id}")]
        public IActionResult EditServices(int id)
        {
            Service service = db.Services.Where(srv => srv.ServiceId == id).FirstOrDefault();
            if(service != null)
            {
                return View(service);
            }
            return RedirectToAction("IndexServices");
        }
        [HttpPost]
        public IActionResult EditServices(Service model)
        {
            if(ModelState.IsValid)
            {
                Service service = db.Services.Where(srv => srv.ServiceId == model.ServiceId).FirstOrDefault();
                if(service != null)
                {
                    service.Libelle = model.Libelle;
                    db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View();
        }
        public IActionResult DeleteServices(int id)
        {
            Service service = db.Services.Where(srv => srv.ServiceId == id).FirstOrDefault();
            if(service != null)
            {
                db.Services.Remove(service);
                db.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

PFAVersionFinale/Controllers/VoteController.cs
using Microsoft.AspNetCore.Mvc;
using PFAVersionFinale.Models;
namespace PFAVersionFinale.Controllers
{
    public class VoteController : Controller
    {
        MyContexte db;
        public VoteController(MyContexte db)
        {
            this.db = db;
        }
        public IActionResult IndexVote()
        {
            List<Vote> votes = db.Votes.ToList();
            return View(votes);
        }
        public IActionResult AddVote()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddVote(Vote vote)
        {
            if (ModelState.IsValid)
            {
                db.Votes.Add(vote);
                db.SaveChanges();
                return RedirectToAction("IndexVote");
            }
            return View();
        }
        [Route("Vote/EditVotes/{id}")]
        public IActionResult EditVotes(int id)
        {
            Vote vote = db.Votes.Where(vte => vte.VoteId == id).FirstOrDefault();
            if (vote != null)
            {
                return View(vote);
            }
            return View();
        }
        [HttpPost]
        public IActionResult EditVote(Vote model) 
        {
            if (ModelState.IsValid)
            {
                Vote vote = db.Votes.Where(vte => vte.VoteId == model.VoteId).FirstOrDefault();
                if(vote != null)
                {
                    vote.NoteVote = model.NoteVote;
                    db.SaveChanges();
                    return RedirectToAction("IndexVote");
                }
            }
            return View();
        }
        [Route("Vote/DeleteVote/{id}")]
        public IActionResult DeleteVote(int id)
        {
            Vote vote = db.Votes.Where(vte => vte.VoteId == id).FirstOrDefault();
            if(vote != null)
            {
                db.Votes.Remove(vote);
                db.SaveChanges();
            }
            return RedirectToAction("IndexVote");
        }
    }
}

PFAVersionFinale/Views/Vote/AddVote.cshtml
@model PFAVersionFinale.Models.Vote
@{
    ViewData["Title"] = "AddVote";
    Layout = "";
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Ajouter Service</title>
	<style type="text/css">
		* {
			margin: 0;
			padding: 0;
			box-sizing: border-box;
			font-family: 'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;
		}

		body {
			color: #fff;
			display: flex;
			height: 100vh;
			justify-content: center;
			align-items: center;
			background: linear-gradient(135deg,#0000FF,#79F8F8);
			padding: 10px;
		}

		.container {
			max-width: 700px;
			width: 100%;
			padding: 25px 30px;
			border-radius: 25px;
			background: linear-gradient(135deg,#1E7FCB,#007FFF);
		}

			.container .heading {
				font-size: 25px;
				font-weight: 500;
				position: relative;
				text-align: center;
				padding: 0 0 20px 0;
			}

				.container .heading::before {
					content: '';
					position: absolute;
					height: 3px;
					left: 0;
					bottom: 0;
					width: 100%;
					background: linear-gradient(135deg,#0000FF,#79F8F8);
				}

			.container form .card-details {
				margin-top: 25px;
				display: flex;
				flex-wrap: wrap;
				justify-content: space-between;
			}

		form .card-details .card-box {
			width: calc(100% / 2 - 20px);
			margin-bottom: 15px;
		}

		.card-details .card-box .details {
			display: block;
			font-weight: 500;
			margin-bottom: 5px;
		}

		.card-details .card-box input {
			height: 45px;
			width: 100%;
			outline: none;
			border-radius: 5px;
			border: 1px solid #ccc;
			padding-left: 15px;
			font-size: 16px;
			border-bottom: 2px;
			transition: all 0.3s ease;
		}

			.card-details .card-box input:focus,
			.card-details .card-box input:valid {
				border-color: #9b59b6;
			}

		form .circal-form .circal-title {
			font-size: 20px;
			font-weight: 500;
			border-bottom: 2px solid;
		}

		form .circal-form .category {
			margin-top: 10px;
			margin-bottom: 10px;
		}

		form .button {
			text-align: center;
		}

			form .button input {
				padding: 10px 0;
				margin-top: 10px;
				height: 100%;
				width: 50%;
				outline: none;
				border: none;
				font-size: 18px;
				color: #fff;
				font-weight: 500;
				border-radius: 5px;
				letter-spacing: 1px;
				background: linear-gradient(135deg,#0000FF,#79F8F8);
			}
	</style>
</head>
<body>
	<div class="container">
		<div class="heading">Information sur le Service</div>
		<form asp-action="AddVote" method="post" asp-controller="Vote">
			<div class="card-details">
				<div class="form-group">
					<label asp-for="DateVote" class="control-label"></label>
					<input asp-for="DateVote" class="form-control" />
					<span asp-validation-for="DateVote" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="NoteVote" class="control-label"></label>
					<input asp-for="NoteVote" class="form-control" />
					<span asp-validation-for="NoteVote" class="text-danger"></span>
				</div>
			</div>
			<div class="btn btn-primary">
				<a asp-action="IndexServices" asp-controller="Services">Add</a>
			</div>
		</form>
	</div>
</body>
</html>

PFAVersionFinale/Views/Vote/DeleteVote.cshtml
@model PFAVersionFinale.Models.Vote

@{
    ViewData["Title"] = "DeleteVote";
    Layout = "";
}

<h1>DeleteVote</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vote</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateVote)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateVote)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoteVote)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoteVote)
        </dd>
    </dl>
    
    <form asp-action="DeleteVote">
        <input type="hidden" asp-for="VoteId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PFAVersionFinale/Views/Vote/EditVotes.cshtml
@model PFAVersionFinale.Models.Vote
@{
    ViewData["Title"] = "EditVotes";
    Layout = "";
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Ajouter Service</title>
	<style type="text/css">
		* {
			margin: 0;
			padding: 0;
			box-sizing: border-box;
			font-family: 'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;
		}

		body {
			color: #fff;
			display: flex;
			height: 100vh;
			justify-content: center;
			align-items: center;
			background: linear-gradient(135deg,#0000FF,#79F8F8);
			padding: 10px;
		}

		.container {
			max-width: 700px;
			width: 100%;
			padding: 25px 30px;
			border-radius: 25px;
			background: linear-gradient(135deg,#1E7FCB,#007FFF);
		}

			.container .heading {
				font-size: 25px;
				font-weight: 500;
				position: relative;
				text-align: center;
				padding: 0 0 20px 0;
			}

				.container .heading::before {
					content: '';
					position: absolute;
					height: 3px;
					left: 0;
					bottom: 0;
					width: 100%;
					background: linear-gradient(135deg,#0000FF,#79F8F8);
				}

			.container form .card-details {
				margin-top: 25px;
				display: flex;
				flex-wrap: wrap;
				justify-content: space-between;
			}

		form .card-details .card-box {
			width: calc(100% / 2 - 20px);
			margin-bottom: 15px;
		}

		.card-details .card-box .details {
			display: block;
			font-weight: 500;
			margin-bottom: 5px;
		}

		.card-details .card-box input {
			height: 45px;
			width: 100%;
			outline: none;
			border-radius: 5px;
			border: 1px solid #ccc;
			padding-left: 15px;
			font-size: 16px;
			border-bottom: 2px;
			transition: all 0.3s ease;
		}

			.card-details .card-box input:focus,
			.card-details .card-box input:valid {
				border-color: #9b59b6;
			}

		form .circal-form .circal-title {
			font-size: 20px;
			font-weight: 500;
			border-bottom: 2px solid;
		}

		form .circal-form .category {
			margin-top: 10px;
			margin-bottom: 10px;
		}

		form .button {
			text-align: center;
		}

			form .button input {
				padding: 10px 0;
				margin-top: 10px;
				height: 100%;
				width: 50%;
				outline: none;
				border: none;
				font-size: 18px;
				color: #fff;
				font-weight: 500;
				border-radius: 5px;
				letter-spacing: 1px;
				background: linear-gradient(135deg,#0000FF,#79F8F8);
			}
	</style>
</head>
<body>
	<div class="container">
		<div class="heading">Information Du Client</div>
		<form asp-action="EditVote" method="post" asp-controller="Vote">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="VoteId" />
			<div class="card-details">
				<div class="form-group">
					<label asp-for="DateVote" class="control-label"></label>
					<input asp-for="DateVote" class="form-control" />
					<span asp-validation-for="DateVote" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="NoteVote" class="control-label"></label>
					<input asp-for="NoteVote" class="form-control" />
					<span asp-validation-for="NoteVote" class="text-danger"></span>
				</div>
			</div>
			<div class="btn btn-primary">
				<a asp-action="EditOuvriers" asp-controller="Services">Add</a>
			</div>
		</form>
	</div>
</body>
</html>