PFAVersionFinale/Models/Client.cs
namespace PFAVersionFinale.Models
{
    public class Client:User
    {

		public int ClientId { get; set; }
        public List<Review>? reviews { get; set; }
        public List<Vote>? votes { get; set; }
        public int VoteId { get; set; }
    }
}

PFAVersionFinale/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PFAVersionFinale.Models;
namespace PFAVersionFinale.Controllers
{
    public class ClientController : Controller
    {
        MyContexte db;
        public ClientController(MyContexte db)
        {
            this.db = db;
        }
        public IActionResult IndexClient()
        {
            List<Client> clients = db.Clients.ToList();
            return View(clients);
        }
        public IActionResult AddClient()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddClient(Client client,IFormFile photo)
        {
            if(ModelState.IsValid)
            {
                if (photo.FileName.EndsWith(".jpeg") || photo.FileName.EndsWith(".png") || photo.FileName.EndsWith(".jpg"))
                {
                    client.photo = photo.FileName;
                    //copier l'image vers le serveur
                    string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Image", photo.FileName);
                    var file = new FileStream(path, FileMode.Create);
                    photo.CopyTo(file);
                    db.Clients.Add(client);
                    db.SaveChanges();
                    return RedirectToAction("IndexClient");
                }
            }
            return View();
        }
        public IActionResult EditClient(int id)
        {
            Client client = db.Clients.Where(clt => clt.ClientId == id).FirstOrDefault();
            if (client != null)
            {
                return View(client);
            }
            return RedirectToAction("IndexClient");
        }
        [HttpPost]
        public IActionResult EditClient(Client model)
        {
            if (ModelState.IsValid)
            {
                Client client = db.Clients.Where(clt => clt.ClientId == model.ClientId).FirstOrDefault();
                if (client != null)
                {
                    client.nom = model.nom;
                    client.prenom = model.prenom;
                    client.telephone = model.telephone;
                    client.email = model.email;
                    client.ville = model.ville;
                    client.photo = model.photo;
                    db.SaveChanges();
                    return RedirectToAction("IndexClient");
                }
            }
            return View();
        }
        public IActionResult DeleteClient(int id)
        {
            Client client = db.Clients.Where(clt => clt.ClientId == id).FirstOrDefault();
            if(client != null)
            {
                db.Clients.Remove(client);
                db.SaveChanges();
            }
            return RedirectToAction("IndexClient");
        }
    }
}

PFAVersionFinale/Controllers/OuvrierController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PFAVersionFinale.Models;

namespace PFAVersionFinale.Controllers
{
    public class OuvrierController : Controller
    {
        MyContexte db;
        public OuvrierController(MyContexte db)
        {
            this.db = db;
        }
        public IActionResult IndexOuvriers()
        {
            return View();
        }
        public IActionResult AddOuvriers()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddOuvriers(Ouvrier ouvrier,IFormFile photo)
        {
            if (ModelState.IsValid)
            {
                if (photo.FileName.EndsWith(".jpeg") || photo.FileName.EndsWith(".png") || photo.FileName.EndsWith(".jpg"))
                {
                    ouvrier.photo = photo.FileName;
                    //copier l'image vers le serveur
                    string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Image", photo.FileName);
                    var file = new FileStream(path, FileMode.Create);
                    photo.CopyTo(file);
                    db.Ouvners.Add(ouvrier);
                    db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View();
        }
        public IActionResult EditOuvriers(int id)
        {
            Ouvrier ouv = db.Ouvners.Where(ouv => ouv.OuvrierId == id).FirstOrDefault();
            if(ouv != null)
            {
                return View(ouv);
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult EditOuvriers(Ouvrier model)
        {
            if (ModelState.IsValid)
            {
                Ouvrier ouv = db.Ouvners.Where(ouve => ouve.OuvrierId == model.OuvrierId).FirstOrDefault();
                if(ouv != null)
                {
                    ouv.nom = model.nom;
                    ouv.prenom = model.prenom;
                    ouv.telephone = model.telephone;
                    ouv.email = model.email;
                    ouv.ville = model.ville;
                    ouv.photo = model.photo;
                    db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        public IActionResult DeleteOuvriers(int id)
        {
            Ouvrier ouvrier = db.Ouvners.Where(ouv => ouv.OuvrierId == id).FirstOrDefault();
            if (ouvrier != null)
            {
                db.Ouvners.Remove(ouvrier);
                db.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

PFAVersionFinale/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using PFAVersionFinale.Models;
namespace PFAVersionFinale.Controllers
{
    public class ServicesController : Controller
    {
        MyContexte db;
        public ServicesController(MyContexte db)
        {
            this.db = db;
        }
        public IActionResult IndexServices()
        {
            List<Service> services = db.Services.ToList();
            return View(services);
        }
        public IActionResult AddServices()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddServices(Service service)
        {
            if (ModelState.IsValid)
            {
                db.Services.Add(service);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [Route("Services/EditServices/{id}")]
        public IActionResult EditServices(int id)
        {
            Service service = db.Services.Where(srv => srv.ServiceId == id).FirstOrDefault();
            if(service != null)
            {
                return View(service);
            }
            return RedirectToAction("IndexServices");
        }
        [HttpPost]
        public IActionResult EditServices(Service model)
        {
            if(ModelState.IsValid)
            {
                Service service = db.Services.Where(srv => srv.ServiceId == model.ServiceId).FirstOrDefault();
                if(service != null)
                {
                    service.Libelle = model.Libelle;
                    db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View();
        }
        public IActionResult DeleteServices(int id)
        {
            Service service = db.Services.Where(srv => srv.ServiceId == id).FirstOrDefault();
            if(service != null)
            {
                db.Services.Remove(service);
                db.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

PFAVersionFinale/Views/Client/AddClient.cshtml
@model PFAVersionFinale.Models.Client
@{
    ViewData["Title"] = "AddClient";
    Layout = "";
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Ajouter Service</title>
	<style type="text/css">
		* {
			margin: 0;
			padding: 0;
			box-sizing: border-box;
			font-family: 'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;
		}

		body {
			color: #fff;
			display: flex;
			height: 100vh;
			justify-content: center;
			align-items: center;
			background: linear-gradient(135deg,#0000FF,#79F8F8);
			padding: 10px;
		}

		.container {
			max-width: 700px;
			width: 100%;
			padding: 25px 30px;
			border-radius: 25px;
			background: linear-gradient(135deg,#1E7FCB,#007FFF);
		}

			.container .heading {
				font-size: 25px;
				font-weight: 500;
				position: relative;
				text-align: center;
				padding: 0 0 20px 0;
			}

				.container .heading::before {
					content: '';
					position: absolute;
					height: 3px;
					left: 0;
					bottom: 0;
					width: 100%;
					background: linear-gradient(135deg,#0000FF,#79F8F8);
				}

			.container form .card-details {
				margin-top: 25px;
				display: flex;
				flex-wrap: wrap;
				justify-content: space-between;
			}

		form .card-details .card-box {
			width: calc(100% / 2 - 20px);
			margin-bottom: 15px;
		}

		.card-details .card-box .details {
			display: block;
			font-weight: 500;
			margin-bottom: 5px;
		}

		.card-details .card-box input {
			height: 45px;
			width: 100%;
			outline: none;
			border-radius: 5px;
			border: 1px solid #ccc;
			padding-left: 15px;
			font-size: 16px;
			border-bottom: 2px;
			transition: all 0.3s ease;
		}

			.card-details .card-box input:focus,
			.card-details .card-box input:valid {
				border-color: #9b59b6;
			}

		form .circal-form .circal-title {
			font-size: 20px;
			font-weight: 500;
			border-bottom: 2px solid;
		}

		form .circal-form .category {
			margin-top: 10px;
			margin-bottom: 10px;
		}

		form .button {
			text-align: center;
		}

			form .button input {
				padding: 10px 0;
				margin-top: 10px;
				height: 100%;
				width: 50%;
				outline: none;
				border: none;
				font-size: 18px;
				color: #fff;
				font-weight: 500;
				border-radius: 5px;
				letter-spacing: 1px;
				background: linear-gradient(135deg,#0000FF,#79F8F8);
			}
	</style>
</head>
<body>
	<div class="container">
		<div class="heading">Information sur l Ouvrier</div>
		<form asp-action="AddOuvriers" method="post" asp-controller="Ouvrier" enctype="multipart/form-data">
			<div class="card-details">
				<div class="card-box">
					<label class="details" for="Nom">Nom:</label>
					<input type="text" name="Nom" required>
				</div>
				<div class="card-box">
					<label class="details" for="prenom">Prenom:</label>
					<input type="text" name="prenom" required>
				</div>
				<div class="card-box">
					<label class="details" for="ville">Ville:</label>
					<input type="text" name="ville" required>
				</div>
				<div class="card-box">
					<label class="details" for="Email">Email:</label>
					<input type="text" name="Email" required>
				</div>
				<div class="card-box">
					<label class="details" asp-for="photo">Photo:</label>
					<input type="file" name="photo" accept="Image/*" />
				</div>
				<div class="card-box">
					<label class="details" for="prenom">Telephone:</label>
					<input type="text" name="prenom" required>
				</div>
			</div>
			<div class="btn btn-primary">
				<a asp-action="IndexOuvriers" asp-controller="Ouvrier">Add</a>
			</div>
		</form>
	</div>
</body>
</html>

PFAVersionFinale/Views/Client/DeleteClient.cshtml
@model PFAVersionFinale.Models.Client
@{
    ViewData["Title"] = "DeleteClient";
    Layout = "";
}
<h1>DeleteClient</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VoteId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VoteId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.telephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ville)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ville)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.login)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.login)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.confirmPassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.confirmPassword)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.role)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDerniereConnection)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDerniereConnection)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.inscription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.inscription.FirstName)
        </dd>
    </dl>
    
    <form asp-action="DeleteClient">
        <input type="hidden" asp-for="UserId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PFAVersionFinale/Views/Client/EditClient.cshtml
@model PFAVersionFinale.Models.Client
@{
    ViewData["Title"] = "EditClient";
    Layout = "";
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Ajouter Service</title>
	<style type="text/css">
		* {
			margin: 0;
			padding: 0;
			box-sizing: border-box;
			font-family: 'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;
		}

		body {
			color: #fff;
			display: flex;
			height: 100vh;
			justify-content: center;
			align-items: center;
			background: linear-gradient(135deg,#0000FF,#79F8F8);
			padding: 10px;
		}

		.container {
			max-width: 700px;
			width: 100%;
			padding: 25px 30px;
			border-radius: 25px;
			background: linear-gradient(135deg,#1E7FCB,#007FFF);
		}

			.container .heading {
				font-size: 25px;
				font-weight: 500;
				position: relative;
				text-align: center;
				padding: 0 0 20px 0;
			}

				.container .heading::before {
					content: '';
					position: absolute;
					height: 3px;
					left: 0;
					bottom: 0;
					width: 100%;
					background: linear-gradient(135deg,#0000FF,#79F8F8);
				}

			.container form .card-details {
				margin-top: 25px;
				display: flex;
				flex-wrap: wrap;
				justify-content: space-between;
			}

		form .card-details .card-box {
			width: calc(100% / 2 - 20px);
			margin-bottom: 15px;
		}

		.card-details .card-box .details {
			display: block;
			font-weight: 500;
			margin-bottom: 5px;
		}

		.card-details .card-box input {
			height: 45px;
			width: 100%;
			outline: none;
			border-radius: 5px;
			border: 1px solid #ccc;
			padding-left: 15px;
			font-size: 16px;
			border-bottom: 2px;
			transition: all 0.3s ease;
		}

			.card-details .card-box input:focus,
			.card-details .card-box input:valid {
				border-color: #9b59b6;
			}

		form .circal-form .circal-title {
			font-size: 20px;
			font-weight: 500;
			border-bottom: 2px solid;
		}

		form .circal-form .category {
			margin-top: 10px;
			margin-bottom: 10px;
		}

		form .button {
			text-align: center;
		}

			form .button input {
				padding: 10px 0;
				margin-top: 10px;
				height: 100%;
				width: 50%;
				outline: none;
				border: none;
				font-size: 18px;
				color: #fff;
				font-weight: 500;
				border-radius: 5px;
				letter-spacing: 1px;
				background: linear-gradient(135deg,#0000FF,#79F8F8);
			}
	</style>
</head>
<body>
	<div class="container">
		<div class="heading">Information sur l Ouvrier</div>
		<form asp-action="EditServices" method="post" asp-controller="Services">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="ClientId" />
			<div class="card-details">
				<div class="card-box">
					<label asp-for="nom" class="control-label"></label>
					<input asp-for="nom" class="form-control" />
					<span asp-validation-for="nom" class="text-danger"></span>
				</div>
				<div class="card-box">
					<label asp-for="prenom" class="control-label"></label>
					<input asp-for="prenom" class="form-control" />
					<span asp-validation-for="prenom" class="text-danger"></span>
				</div>
				<div class="card-box">
					<label asp-for="telephone" class="control-label"></label>
					<input asp-for="telephone" class="form-control" />
					<span asp-validation-for="telephone" class="text-danger"></span>
				</div>
				<div class="card-box">
					<label asp-for="ville" class="control-label"></label>
					<input asp-for="ville" class="form-control" />
					<span asp-validation-for="ville" class="text-danger"></span>
				</div>
				<div class="card-box">
					<label asp-for="email" class="control-label"></label>
					<input asp-for="email" class="form-control" />
					<span asp-validation-for="email" class="text-danger"></span>
				</div>
				<div class="card-box">
					<label class="details" asp-for="photo">Photo:</label>
					<input type="file" name="photo" accept="Image/*" />
				</div>
			</div>
			<div class="btn btn-primary">
				<a asp-action="EditOuvriers" asp-controller="Services">Add</a>
			</div>
		</form>
	</div>
</body>
</html>