PFAVersionFinale/Controllers/OuvrierController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PFAVersionFinale.Models;

namespace PFAVersionFinale.Controllers
{
    public class OuvrierController : Controller
    {
        MyContexte db;
        public OuvrierController(MyContexte db)
        {
            this.db = db;
        }
        public IActionResult IndexOuvriers()
        {
            return View();
        }
        public IActionResult AddOuvriers()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddOuvriers(Ouvrier ouvrier,IFormFile photo)
        {
            if (ModelState.IsValid)
            {
                if (photo.FileName.EndsWith(".jpeg") || photo.FileName.EndsWith(".png") || photo.FileName.EndsWith(".jpg"))
                {
                    ouvrier.photo = photo.FileName;
                    //copier l'image vers le serveur
                    string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Image", photo.FileName);
                    var file = new FileStream(path, FileMode.Create);
                    photo.CopyTo(file);
                    db.Ouvners.Add(ouvrier);
                    db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View();
        }
        public IActionResult EditOuvriers(int id)
        {
            Ouvrier ouv = db.Ouvners.Where(ouv => ouv.OuvrierId == id).FirstOrDefault();
            if(ouv != null)
            {
                return View(ouv);
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult EditOuvriers(Ouvrier model)
        {
            if (ModelState.IsValid)
            {
                Ouvrier ouv = db.Ouvners.Where(ouve => ouve.OuvrierId == model.OuvrierId).FirstOrDefault();
                if(ouv != null)
                {
                    ouv.nom = model.nom;
                    ouv.prenom = model.prenom;
                    ouv.telephone = model.telephone;
                    ouv.email = model.email;
                    ouv.ville = model.ville;
                    ouv.photo = model.photo;
                    db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        public IActionResult DeleteOuvriers(int id)
        {
            Ouvrier ouvrier = db.Ouvners.Where(ouv => ouv.OuvrierId == id).FirstOrDefault();
            if (ouvrier != null)
            {
                db.Ouvners.Remove(ouvrier);
                db.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

PFAVersionFinale/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using PFAVersionFinale.Models;
using System.Net.Mail;
using System.Net;
namespace PFAVersionFinale.Controllers
{
    public class UsersController : Controller
    {
        MyContexte db;
        public UsersController(MyContexte db)
        {
            this.db = db;
        }
        public IActionResult IndexUsers()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(User user)
        {
            string msg = "";
            if (ModelState.IsValid)
            {
                WebMaster wm = db.WebMasters.FirstOrDefault(wb => wb.email == user.email && wb.password == user.password);
                if (wm != null)
                {
                    HttpContext.Session.SetString("Name", user.nom + " " + user.prenom);
                    HttpContext.Session.SetString("Role", "Web MAster");
                    HttpContext.Session.SetString("Id", user.UserId.ToString());
                    return RedirectToAction("../User/WebMaster/Index");
                }
                Client clt = db.Clients.FirstOrDefault(u => u.email == user.email && u.password == user.password);
                if (clt != null)
                {
                    HttpContext.Session.SetString("Name", user.nom + " " + user.prenom);
                    HttpContext.Session.SetString("Role", "Web MAster");
                    HttpContext.Session.SetString("Id", user.UserId.ToString());
                    return RedirectToAction("../User/Client/Index");
                }
                else
                {
                    Ouvrier o = db.Ouvners.FirstOrDefault(s => s.email == user.email && s.password == user.password);
                    if (o != null)
                    {
                        HttpContext.Session.SetString("Name", user.nom + " " + user.prenom);
                        HttpContext.Session.SetString("Role", "Web MAster");
                        HttpContext.Session.SetString("Id", user.UserId.ToString());
                        return RedirectToAction("../User/Ouvrier/Index");
                    }
                }
            }
            msg = "Login/password Incorrecte";
            ViewBag.msg = msg;
            return View();
        }
        public IActionResult Inscription()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Inscription(Inscription inscription)
        {
            if (ModelState.IsValid)
            {
                int count = db.Inscriptions.Where(us => us.Email == inscription.Email).Count();
                //int count = db.users.Where(us => us.Login == inscription.Email).Count();
                if (count == 0)
                {
                    //User user1 = new User(user);
                    db.Inscriptions.Add(inscription);
                    db.SaveChanges();
                    HttpContext.Session.SetString("Nom", inscription.FirstName);
                    HttpContext.Session.SetString("Prenom", inscription.LastName);
                    HttpContext.Session.SetString("Email", inscription.Email);
                    return RedirectToAction("Index", "Inscription");
                }
                ModelState.AddModelError("Login", "Login déja exists!");
            }
            return View();
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }
        private static string GenerateRandomPassword()
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
            var random = new Random();
            var password = new string(Enumerable.Repeat(chars, 10).Select(s => s[random.Next(s.Length)]).ToArray());
            return password;
        }
        public IActionResult forgotPassword()
        {
            return View();
        }
        [HttpPost]
        public IActionResult forgotPassword(User user)
        {
            if (ModelState.IsValid)
            {
                int count = db.Users.Where(us => us.email == user.email).Count();
                if (count == 0)
                {
                    //User user = new User(model);
                    user.password = GenerateRandomPassword();
                    db.Users.Add(user);
                    db.Update(user.password);
                    db.SaveChanges();
                    HttpContext.Session.SetString("Nom", user.nom);
                    HttpContext.Session.SetString("Prenom", user.prenom);
                    HttpContext.Session.SetString("Role", user.role);
                    return RedirectToAction("Index", "Inscription");
                }
                ModelState.AddModelError("Login", "Login déja exists!");
            }
            var email = new MailMessage();
            email.From = new MailAddress("votreadresseemail@votredomaine.com");
            email.To.Add(new MailAddress(user.email));
            email.Subject = "Confirmation d'inscription";
            email.Body = "Bonjour " + user.nom + user.prenom + ",<br/><br/>" +
                     "Merci de vous être inscrit sur notre site web. " +
                     "Pour confirmer votre inscription, veuillez cliquer sur le lien suivant :<br/><br/>" +
                     "<a href='" + Url.Action("ConfirmerInscription", "Inscription", new { code = user.InscriptionId }, "http") + "'>Confirmer votre inscription</a><br/><br/>" +
                     "Si vous n'êtes pas à l'origine de cette inscription, ignorez simplement ce message.<br/><br/>" +
                     "Cordialement,<br/>L'équipe de notre site web.";
            var smptClient = new SmtpClient();
            smptClient.Host = "localhost";
            smptClient.Port = 7008;
            smptClient.UseDefaultCredentials = false;
            smptClient.Credentials = new NetworkCredential("votreadresseemail@votredomaine.com", "votre_mot_de_passe");
            smptClient.EnableSsl = true;
            smptClient.Send(email);
            return View("Login", user);
        }
    }
}

PFAVersionFinale/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Allo Service</title>
    <!-- Favicon-->
    <link rel="icon" type="image-icon" href="~/assets/favicon.ico" />
    <!-- Bootstrap Icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />
    <base href="~/" />
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#page-top">Allo Service</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                    <li class="nav-item"><a class="nav-link" href="#portfolio">Profile</a></li>
                    <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Service" asp-action="DetailService">CatalogueService</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Ouvrier" asp-action="DetailOurvrier">CatalogueOuvrier</a></li>
                    @if (Context.Session.GetString("Nom") == null)
                    {
                        <li class="nav-item"><a class="nav-link" asp-controller="Users" asp-action="Login">Login</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Users" asp-action="Inscription">Inscription</a></li>
                    }
                    else
                    {
                        <li class="nav-item"><a class="nav-link" asp-controller="" asp-action="Login">@Context.Session.GetString("Nom") @Context.Session.GetString("Prenom") (@Context.Session.GetString("Role"))</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Users" asp-action="Logout">Se Deconnecter</a></li>
                    }
                    @*<li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Login</a>
                    <div class="dropdown-menu">
                    <a class="dropdown-item" href="~/Ouvrier/login.html>Ouvrier</a>
                    <a class="dropdown-item" href="~/Client/login.html">Client</a>
                    <a class="dropdown-item" href="~/WebMaster/login.html">Web Master</a>
                    </div>
                    </li>*@
                </ul>
            </div>
        </div>
    </nav>

    <div class="w-100">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- Footer-->
    <footer class="bg-light py-5">
        <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2023 - Company Name</div></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- SimpleLightbox plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

    @RenderSection("Scripts", false)
</body>
</html>